Implement display wakeup on Linux
haimgel/display-switch pull request #94
Opened 2022-05-03 03:08 UTC by thirtythreeforty

Fixes #27.  Based solely on testing on my Ryzen integrated graphics and Dell
monitor.  All commands sent over DisplayPort.

I attempted to wiggle the mouse, but that worked very inconsistently, while
pressing a key works basically every time.  I wish there were a truly no-op key
to press, but I don't know of one.

2022-05-29 19:14 UTC, haimgel requested changes

2022-05-29 19:14 UTC, haimgel commented on Cargo.toml
> +uinput = "0.1.3"
Could you please move this to the `[target.'cfg(target_os = "linux")'.dependencies]` section below? This breaks builds on macOS and Windows

2022-05-29 19:14 UTC, haimgel commented on src/platform/wake_displays.rs
> +
This looks good, but it fails the test below, at least on Github: https://github.com/haimgel/display-switch/runs/6644547179?check_suite_focus=true

Do you think it's because Github builders run headless? Perhaps the test below it not really helpful and should be removed outright... It's not testing much.

2022-05-29 19:15 UTC, haimgel commented
@thirtythreeforty, thanks for the PR, glad you took a look at it. There's a small issue with building on non-Linux machines, though.

2023-04-29 19:30 UTC, micwoj92 commented
This branch has conflicts that must be resolved

2023-10-22 12:46 UTC, haimgel commented
Closing in favor of #126

2023-10-22 12:46 UTC, closed without merging